justemutarkov/Server

- src/item/helpFunctions.js
Found when trying to purchase an item that has an alternate currency from the trader.
(Skier items that are priced with Euros)
(Peacekeeper dollar exchange will use dollars as the count of roubles when exchanging for dollars)
Changed it so that the _tpl used is not based on trader currency but the barter item _tpl. (This should only apply for money based barters)
> fixed alternate currency barters

- src/bots.js
- src/caching/_route.js
- src/item/_move.js
- src/item/helpFunctions.js
- src/profile.js
- src/response.js
This change reworks scav generation so that they are saved to a json file like character.json. Instead of generating a scav every time profiles are loaded, the server will now generate a scav when it's explicitly requested to do so by the client (previously, this was a no-op). This means that one generated scav will stay with you until he dies or escapes.
This change also introduces changes to the item function to support inventory transfer at the end of a successful raid from a player scav. Some item functions have been refactored to take in a single profile as the argument instead of a list of two profiles (main + scav).
Profile saving function also required some modifications.
> Make server-side changes to support player scavs.

- src/item/_trade.js
change array was empty when writing the response (output)
Items should now appear after purchasing from ragfair using the "purchase all" option in the preset menu.
> Fixed preset ragfair buying

- src/trader.js
calculation of the target level was not functioning correctly so i decided to do it over. Initial value will start at 0 because the first check will always result in the user being level 1. Highest level is 4 so will only add to targetLevel if less than that.
> trader level fixes 2.0 electric boogaloo

- src/server/_start.js
Some maps are called with non-lowercase names in API, while array of maps is in lowercase.
Example, selected Interchange, click Next, Next, enable PvE & Bosses, Next, Insure items Next, Ready
Game eventually loads into an empty map
```
[NaN][127.0.0.1] /api/location/Interchange
[ERROR] Server: 1.0.0
[ERROR] Game: 0.12.2.5485
[ERROR] Trace:
TypeError: Cannot convert undefined or null to object
at Function.keys (<anonymous>)
at Object.get (C:\Games\EscapeFromTarkov\EmuTarkov-Server\src\response\_map.js:7:30)
at sendResponse (C:\Games\EscapeFromTarkov\EmuTarkov-Server\src\server\_start.js:153:25)
at handleRequest (C:\Games\EscapeFromTarkov\EmuTarkov-Server\src\server\_start.js:173:9)
at Server.https.createServer (C:\Games\EscapeFromTarkov\EmuTarkov-Server\src\server\_start.js:234:9)
at …
```
> Always lower-case map name

- db/quests/59c512ad86f7741f0d09de9b.json
- db/quests/5a0327ba86f77456b9154236.json
Fix Spa Tour Part 3 requiring 3 Clin Wiper, Corrugated Hose, and Ox Bleach instead of 2.
https://escapefromtarkov.gamepedia.com/Spa_Tour_-_Part_3
Fix Punisher Part 3 requiring 50 Scav Kills instead of 25.
https://escapefromtarkov.gamepedia.com/The_Punisher_-_Part_3
> Spa Tour Part 3 & Punisher Part 3 Counter Fixes

- src/item/helpFunctions.js
… and won't push existing stacks over their max value.
Hi,
Here's an attempt at fixing bug #199 (if confirmed). To make things simpler and more sensible, money from sells should now be forced into the player's stash. The stack limit depends on the currency (500k for RUB, 50k for EUR/USD).
Let me know if you think using the character's equipment inventory is still a viable option.
Note: this should fix existing stacks not going over the limit, but it seems that the rest of the function (at the _addedMoney_ label) can still create a single stack of all the money that could not fit into an existing stack. For example, selling the gamma container for a few million RUB will end up having a huge stack of cash in the stash. While still a problem, the player can then ctrl+click the stack to split …
> Money from sells won't go into the character's equipment

- src/classes/move.js
- Object doesn't have `splice`
- Two different variables shared same name, refactored `transferItem` function (`classes/move.js`) overall
There was a crash due to `item` not having `splice` function, since it's an object.
Not sure what the intention with the splice was.
I noticed this occurs when moving a full stack onto another stack, I think I fixed it properly.
> Fixes a crash while stacking items

- src/classes/helpfunc.js
That's only a tiny contribution. In helpfunc::getMoney() for-loop, item._tpl is always equal to currency which is constant, so there's no need to fetch item files to recompute maxStackSize every time.
> Small optimization: put a constant out of a loop

- src/classes/dialogue.js
For some quests, I never get the reward items. The dialogue entry is
always marked as received.
The reason for this seems to be parentId and slotId are missing for these
items. Example: quest 5d25cf2686f77443e75488d4 (Jaeger-Tough Guy)
rewards.Success.items are missing those keys. As a result, dialogue.json
is missing them as well and the message won't display the reward.
A quick fix for this is to mimic what's already done for orphaned items.
Doing so, the items get the trader stash as parent and are ready to
be collected.
> Should fix some quest reward items not being given

- src/classes/helpfunc.js
- src/classes/hideout.js
- src/classes/move.js
- src/classes/preset.js
- src/classes/ragfair.js
- src/loadorder.json
Here's another attempt at fixing the Flea Market (and the hideout).
I tried to avoid modifying too much code. We can then improve and optimize the code if that merges.
So here's what's on this branch:
- a preset.js that handles some preset stuff. I'm not really happy using a class for this. A simple global var and a few function should do it, not sure what's cleaner ;
- basically, item presets are pulled from globals.data, then fed into a lookup table so that we can find all presets that apply to a given template item in O(1) ;
- ragfair now creates offers for all items as before, and also for all presets. This enables having operational weapons on the market, all variants (for those who want to try a specific preset), but also the base receivers as before (for those who want to mod from …
> Flea Market weapons

- src/classes/ragfair.js
I'm reworking ragfair.js but until it's done, here's a fix.
Disables presets when buying build parts in createOffer().
Sets all offer prices to the actual price.
> Fix for #258 wrong price when buying preset parts

- src/classes/preset.js
- src/classes/status.js
A fix for #267 
itemPresets can now give back the base item's TPL (given a preset ID), which helps examining preset items.
> Fix #267 examine preset weapon

- src/classes/helpfunc.js
- src/classes/ragfair.js
A lot of modifications here. Sorry for sending that much to review at a time.
- Added feature: RequiredSearch (it's a reversed LinkedSearch)
- Added a lookup table in helpfunc to remove many loops.
- Code is better, searches are O(1). Mem footprint is very low.
Feel free to move the lookup table and its functions elsewhere.
- LinkedSearch now uses Sets to remove duplicates. Unfortunately,
I can't find a better way of concat them other than the spread operator.
- Flea Market categories are now correctly tallied (take presets into account)
> Ragfair rework and RequiredSearch

- src/classes/trader.js
If I understand correctly, the tpl in the response is the currency to display (not the item template).
If I put the tpl for RUB, I get RUB. Same for USD. If I put an item tpl, I get the trade icon, which should explain the bug.
> Fix #244 wrong currency display when selling items

- src/classes/move.js
- src/classes/trade.js
Maybe not the best solution but it should do for now.
This only works because ragfair/fence items have id=tpl. Otherwise I guess we could just bypass the assort cache and read the assort file directly.
Should fix server crash when buying at market and unlock #147 debugging (that may even solve it).
> Fix for #294

- src/classes/ragfair.js
That's a patch for issue #258 (incorrect price when assembling preset) which was already fixed by 73534f3b4ee288030d69e90a013119968cfc33d3 but, unfortunately, overwritten by mistake by 7abf41400e031bdf36c67c925de10742b274c49f
Sorry for that mistake.
> Fix #258 again

- src/classes/dialogue.js
- src/classes/quest.js
Fix for #318 and also quest weapons being incomplete.
Removed an id replacement that breaks the item hierarchy so quests give full weapons now.
Added quest starter items to messages when the quest is accepted.
Factored quest items retrieval because it's the same for quest Started and quest Success.
> Fix quest rewards #318

- src/classes/hideout.js
Just a typo that crashes the server when upgrading the stash (reported by a friend)
> Fixed hideout leveling stash

- src/classes/quest.js
I've been too confident when fixing the money handover for quests and I've missed one special case: weapon assembly. Those are the quests where you need to handover a full weapon (for Mechanic).
The current code does not handle this at all, hence this fix.
Interestingly enough, the previous code (with money bug) did handle it, but with a sneaky bug: the client only sends the id of the base weapon to remove (not the attachments). So handing over a weapon would remove the receiver from the player's inventory but leave the attachments without any parent. And that's the reason I had these errors on the client logs! item xxx has no parent with id yyy.
That's one more mystery solved :)
For the records, here's a list of all condition types (from which I recon only handoverItem and WeaponAssembly …
> Fixed handover weapons for Mechanic quests

- src/classes/userbuilds.js
Apparently, the client sends us the id of the preset to delete, not the name.
> Fix delete user builds

- src/classes/offraid.js
Quest items are not removed on death. This should address it. Also, it wipes the fastPanel as these ids are not valid anymore.
> Remove quest items on death

- dev/src/test.js
All tests are verified as passing on 0.12.4. Closes #405 and reduces confusion by not referencing non-targeted version.
> Update gameVersion in test.js

- src/classes/insurance.js
Adds a fallback to handle if the item isn't present in db.templates for some reason (newly added to game or added by mod). If such an item is checked for insurance (or insured) it will use the items database price instead of it's template price. The relevant function getItemPrice() should be moved to a more appropriate location later in development.
Closes #415
> Use db.item as fallback

- src/classes/insurance.js
insuredItem is only an itemId. As such the check for slotId was failing to catch the relevant items. Then the parenting code (now at Ln59) would change their slotId which removes the protections that those items have from being removed in offraid.
The loop is a bodge to protect the items within the secure container from having their insurance applied/removed. Will relocate this loop to helpers eventually, but this resolves the issues for now.
Closes #368 
Closes #369
> Fixing Insurance Exceptions
