justemutarkov/Server

project/src/profile.js
https://github.com/justemutarkov/EmuTarkov-Server/pull/25/commits/9b11a9bdd7962beee114f5fc86df6fdc5c37af9f
=> Fixed typo in mail change

src/item/_trade.js, src/item/helpFunctions.js, src/profile.js, src/response.js
Reference Issue #75 
Selling to peacekeeper will now use the correct conversion and give USD to the player. (Should work in theory with EURO based trader as well but untested.)
=> fixed peacekeeper currency bug

src/item/helpFunctions.js
applied 2 step conversion to selling money. Solves dollar value being converted as RUB
=> fixed peacekeeper selling bug

db/maps/bigmap2.json, db/maps/bigmap3.json, db/maps/bigmap4.json, db/maps/bigmap5.json, db/maps/bigmap6.json, db/maps/interchange1.json, db/maps/interchange2.json, db/maps/interchange3.json, db/maps/interchange4.json, db/maps/interchange5.json, db/maps/interchange6.json, db/maps/shoreline1.json, db/maps/shoreline2.json, db/maps/shoreline3.json, db/maps/shoreline4.json, db/maps/shoreline5.json, db/maps/shoreline6.json, db/maps/woods1.json, db/maps/woods2.json, db/maps/woods3.json, db/maps/woods4.json, db/maps/woods5.json
Regex was too loose and I hit replace all twice :(
=> Fix typos in map spawns.

src/item/_move.js
Item discarding through inventory sends body differently to this function. Uses the value for the key item within the body array which allows this function to identify which item to delete in array toDo
=> Discarding item fix

src/classes/profile.js
Price computation of selling items and their children is now correct. Uses memoization to avoid useless loops on inventories.
Feel free to check, comment, pull, test, reject, whatever.
Note: as stated in #189 item prices are not updated when merging/dismantling weapons while in trader's selling UI.
=> Fixes part.1 of price bug #189.

src/classes/map.js
Builds all static loots randomly, then add random dynamic loots
up to server.config maploot settings. Details on issue #207
Filling up loots until we reach lootCount is very nice.
=> Randomizes map loot

core/caching/mods.js
=> Small typo fix

src/classes/health.js
The info object doesn't have an "item" field, only "type", "bodyPart" and "value". This should fix the health saving issue.
=> Fix for health updating and saving

src/classes/trade.js
Small fix to reflect recent changes in export functions
=> Small fix for trade

src/classes/quest.js
I hope it doesn't break anything. I've done some testings and it seems to be working fine.
This should address the issue when the quest resets to "not accepted" when you accept it, then leave the game without going to raid.
I could see two potential problems. First, the client seems to serialize the enum EQuestStatus to a string rather than an int. Second, because of quests resetting, every time we re-accept a quest we create a duplicate in character.json.
So basically, I've changed the status to string and added a check to avoid duplicates. Also, I've removed a needless for loop (backendCounters being a dictionary, we can access them directly). 
Note: in my testings, after I've completed a quest, I got the reward right away in my messages, even though I didn't get a notification about a …
=> Fixes quest accept issue

src/classes/ragfair.js
LinkedSearch on magazines now show ammo
=> Quick fix for #256

src/classes/ragfair.js
Note: the server doesn't start (broken state) so I cannot test.
Please consider testing before merging.
=> Should fix #276

src/classes/status.js
=> Fix for #241, notification clear issue

src/classes/helpfunc.js, src/classes/staticdata.js
Just an ugly hack so that the server starts again, until it's really fixed.
=> Temporary fix for startup issue.

src/classes/hideout.js
=> Fix scav case production start

src/classes/trader.js
=> Fix for incorrect selling prices

src/classes/trader.js
Rewrote findAndReturnChildren( ) to avoid duplicate functions.
=> Code optimization

src/classes/trader.js
Integrated memorization code from emperor06
=> Code integration and optimization

src/classes/bots.js, src/classes/helpfunc.js, src/classes/trader.js
- Fix for player scav spawning with secure container.
- Code optimization for trader.js and helper functions.
=> Bunch of fixes

src/classes/quest.js
Handing over money to quest givers should now work as expected.
I only tried on an old branch and it seems to work. I turned an item, it was ok. I turned 2 out of 3 items, all good. I turned 400k RUB while having more, no problem. I tried with only 150k in my inventory, it correctly turned 150k and the quest now shows 150,000/400,000.
Now it needs to be tested on the current version. I hope lovely testers can help.
Note, I did copy and modify a function from customization in haste (very nice code). I guess this can be refactored.
=> Quest handover item handles money

src/classes/customization.js, src/classes/trader.js, src/responses/trader.js
=> fix Issue #273

src/classes/quest.js
I'm happy this could be fixed by altering a single function, even though that function is now pretty complicated.
Here's what's going on. The previous getQuestRewardItems() was taking all the items from the quest rewards and put them in an array, so they could be sent to dialogue.js which handles mail and attachments.
The problem arises when the reward has 2 identical weapons. Instead of giving us 2 sets of items (1 per weapon), we get a single receiver item with a count of 2, and a list of mods common to all receivers.
This new function starts with gathering all main items (targets), then split them into stacks respecting their maxStackSize. So a receiver with a count of 2 becomes 2 receivers (count=1), a stack of 300k RUB stays the same, and 120 bullets become 2 stacks of 60 if that's …
=> Fix for #356 Incomplete quest items part.2

src/classes/helpfunc.js, src/classes/quest.js
Follow up PR to #362 
I tried to make the code cleaner and more reusable. i think it's much better now. Let me know if there's more to improve.
=> Code quality: make getQuestRewardItems() cleaner

.gitignore, src/classes/hideout.js, src/responses/hideout.js
=> rename hideout functions to not include hideout in the name

src/classes/bots.js
A quick fix so scav players are not given a secured container.
=> Fix #270 Scav Player has a secured container

src/classes/trader.js
fix open fence generating items every time
fix cannot examine fence items
=> fix trader error

src/classes/account.js
Adds the ability to create profiles automatically anytime a new username/e-mail is used.
This is the starting framework for a more feature-rich launcher in the future. 
If this change is not considered viable for inclusion in the server I will release it as a mod instead.
Implements the feature I requested in #407
=> Account Creation

src/classes/dialogue.js, src/classes/hideout.js, src/classes/insurance.js, src/classes/keepalive.js, src/classes/trader.js
Proper operation of the miner is partially tested and the collection should function.
Closes #413
The dialogue restructure should prevent the error mentioned in #412
Closes #412 
Fixed a small issue caused by makese in trader.js, this fix utilizes his work for filter, but I did NOT verify any of the functionality beyond persistence of customization that are purchased.
Closes #401
=> Closing Issues

dev/src/test.js
decode()
Change e-mail
encode()
Unless I'm a dummy this should fix the test failures on @InNoHurryToCode recent commits.
=> Update login test
